[project]
name = "hck2609"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jasperas", email = "15309853+jasperas@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dash>=4.4.1",
    "open-jev",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-frontmatter>=1.3.0",
    "python-pptx>=1.0.2",
    "streamlit>=1.64.0",
]

[project.scripts]
hck2609 = "hck2609:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]

[tool.uv.workspace]
members = [
    "src/hck2609/open-jev",
]

[tool.uv.sources]
open-jev = { workspace = true, editable = true }
